# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/workspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/workspace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/CMakeFiles /home/ubuntu/workspace/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run_mm.o

# Build rule for target.
run_mm.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_mm.o
.PHONY : run_mm.o

# fast build rule for target.
run_mm.o/fast:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/build
.PHONY : run_mm.o/fast

src/FreeList.o: src/FreeList.cpp.o
.PHONY : src/FreeList.o

# target to build an object file
src/FreeList.cpp.o:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/FreeList.cpp.o
.PHONY : src/FreeList.cpp.o

src/FreeList.i: src/FreeList.cpp.i
.PHONY : src/FreeList.i

# target to preprocess a source file
src/FreeList.cpp.i:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/FreeList.cpp.i
.PHONY : src/FreeList.cpp.i

src/FreeList.s: src/FreeList.cpp.s
.PHONY : src/FreeList.s

# target to generate assembly for a file
src/FreeList.cpp.s:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/FreeList.cpp.s
.PHONY : src/FreeList.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/MemPool.o: src/MemPool.cpp.o
.PHONY : src/MemPool.o

# target to build an object file
src/MemPool.cpp.o:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/MemPool.cpp.o
.PHONY : src/MemPool.cpp.o

src/MemPool.i: src/MemPool.cpp.i
.PHONY : src/MemPool.i

# target to preprocess a source file
src/MemPool.cpp.i:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/MemPool.cpp.i
.PHONY : src/MemPool.cpp.i

src/MemPool.s: src/MemPool.cpp.s
.PHONY : src/MemPool.s

# target to generate assembly for a file
src/MemPool.cpp.s:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/MemPool.cpp.s
.PHONY : src/MemPool.cpp.s

src/MemoryManager.o: src/MemoryManager.cpp.o
.PHONY : src/MemoryManager.o

# target to build an object file
src/MemoryManager.cpp.o:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/MemoryManager.cpp.o
.PHONY : src/MemoryManager.cpp.o

src/MemoryManager.i: src/MemoryManager.cpp.i
.PHONY : src/MemoryManager.i

# target to preprocess a source file
src/MemoryManager.cpp.i:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/MemoryManager.cpp.i
.PHONY : src/MemoryManager.cpp.i

src/MemoryManager.s: src/MemoryManager.cpp.s
.PHONY : src/MemoryManager.s

# target to generate assembly for a file
src/MemoryManager.cpp.s:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/MemoryManager.cpp.s
.PHONY : src/MemoryManager.cpp.s

src/TestMManager.o: src/TestMManager.cpp.o
.PHONY : src/TestMManager.o

# target to build an object file
src/TestMManager.cpp.o:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/TestMManager.cpp.o
.PHONY : src/TestMManager.cpp.o

src/TestMManager.i: src/TestMManager.cpp.i
.PHONY : src/TestMManager.i

# target to preprocess a source file
src/TestMManager.cpp.i:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/TestMManager.cpp.i
.PHONY : src/TestMManager.cpp.i

src/TestMManager.s: src/TestMManager.cpp.s
.PHONY : src/TestMManager.s

# target to generate assembly for a file
src/TestMManager.cpp.s:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/TestMManager.cpp.s
.PHONY : src/TestMManager.cpp.s

src/vlgrid.o: src/vlgrid.cpp.o
.PHONY : src/vlgrid.o

# target to build an object file
src/vlgrid.cpp.o:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/vlgrid.cpp.o
.PHONY : src/vlgrid.cpp.o

src/vlgrid.i: src/vlgrid.cpp.i
.PHONY : src/vlgrid.i

# target to preprocess a source file
src/vlgrid.cpp.i:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/vlgrid.cpp.i
.PHONY : src/vlgrid.cpp.i

src/vlgrid.s: src/vlgrid.cpp.s
.PHONY : src/vlgrid.s

# target to generate assembly for a file
src/vlgrid.cpp.s:
	$(MAKE) -f CMakeFiles/run_mm.o.dir/build.make CMakeFiles/run_mm.o.dir/src/vlgrid.cpp.s
.PHONY : src/vlgrid.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... run_mm.o"
	@echo "... src/FreeList.o"
	@echo "... src/FreeList.i"
	@echo "... src/FreeList.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/MemPool.o"
	@echo "... src/MemPool.i"
	@echo "... src/MemPool.s"
	@echo "... src/MemoryManager.o"
	@echo "... src/MemoryManager.i"
	@echo "... src/MemoryManager.s"
	@echo "... src/TestMManager.o"
	@echo "... src/TestMManager.i"
	@echo "... src/TestMManager.s"
	@echo "... src/vlgrid.o"
	@echo "... src/vlgrid.i"
	@echo "... src/vlgrid.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

